name: Publish
on:
  push:
    tags: [ 'v*' ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Note, test in `./test/options` require SSH to pass the LANG env variable
      # However, I failed to enable it
      # Paliative solution is to pass the CI_DISABLE_SSH_ENV var to disable testing
      - run: sudo apt install -y openssh-server && sudo sed -E -i 's|^#?(PermitUserEnvironment)\s.*|\1 yes|' /etc/ssh/sshd_config  && sudo systemctl start sshd
      - run: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
      - run: cat ~/.ssh/id_ed25519.pub > ~/.ssh/authorized_keys
      - run: yarn --frozen-lockfile
      - run: CI_DISABLE_SSH_ENV=1 yarn run test
  publish:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
